# AWS Configuration
regions:
  primary: eu-central-1
  secondary: eu-west-1


# Instance configuration
test_instances:
  - name: web-server-1
    type: t3.medium
    tags:
      Environment: development
      Schedule: office-hours
      Project: carbon-aware-finops
  
  - name: app-server-1
    type: t3.large
    tags:
      Environment: development
      Schedule: office-hours
      Project: carbon-aware-finops
  
  - name: db-server-1
    type: t3.xlarge
    tags:
      Environment: development
      Schedule: 24x7-low-carbon
      Project: carbon-aware-finops
  
  - name: batch-processor-1
    type: t3.large
    tags:
      Environment: development
      Schedule: weekend-off
      Project: carbon-aware-finops

# CloudWatch configuration
monitoring:
  metrics_namespace: CarbonAwareFinOps
  log_group: /aws/carbon-aware-finops
  dashboard_name: carbon-aware-finops-dashboard

# Cost allocation tags
cost_tags:
  - Project
  - Environment
  - Schedule
  - Owner