# Scheduling rules for different instance groups
always-on:
  name: "24/7 Always Running"
  shutdown_time: null
  startup_time: null
  days: []
  carbon_threshold: null  # No restrictions
  timezone: "Europe/Berlin"

office-hours-weekdays:
  name: "Office Hours + Weekend Shutdown"
  shutdown_time: "18:00"
  startup_time: "08:00"
  days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
  carbon_threshold: null
  timezone: "Europe/Berlin"

development-extended:
  name: "Extended Development Hours"
  shutdown_time: "20:00"
  startup_time: "07:00"
  days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
  carbon_threshold: 500  # Optional: Carbon optimization
  timezone: "Europe/Berlin"

carbon-optimized:
  name: "Carbon-Aware 24/7"
  shutdown_time: null
  startup_time: null
  days: []
  carbon_threshold: 300  # Only during low CO2 emissions
  timezone: "Europe/Berlin"